// Generated by https://quicktype.io
export interface Guild {
    id: string;
    name: string;
    description: string;
    ownerId: string;
    icon: string;
    splash: string;
    banner: string;
    homeHeader: string;
    features: string[];
    preferredLocale: string;
    roles: Record<string, Role>;
    afkChannelId: string | null;
    afkTimeout: number;
    systemChannelId: string;
    verificationLevel: number;
    joinedAt: string;
    defaultMessageNotifications: number;
    mfaLevel: number;
    application_id: null;
    explicitContentFilter: number;
    vanityURLCode: string;
    premiumTier: number;
    premiumSubscriberCount: number;
    premiumProgressBarEnabled: boolean;
    systemChannelFlags: number;
    discoverySplash: string;
    rulesChannelId: string;
    safetyAlertsChannelId: string;
    publicUpdatesChannelId: string;
    maxStageVideoChannelUsers: number;
    maxVideoChannelUsers: number;
    maxMembers: number;
    nsfwLevel: number;
    hubType: null;
    latestOnboardingQuestionId: string;
    inventorySettings: InventorySettings;

    getIconURL(): string;
}

interface InventorySettings {
    isEmojiPackCollectible: boolean;
}

interface Role {
    id: string;
    name: string;
    permissions: string;
    mentionable: boolean;
    position: number;
    originalPosition: number;
    color: number;
    colorString: null | string;
    hoist: boolean;
    managed: boolean;
    tags?: Tags;
    icon: null | string;
    unicodeEmoji: null | string;
    flags: number;
}

interface Tags {
    bot_id?: string;
    premium_subscriber?: null;
}

interface GuildStore {
    getGuild(id: string): Guild | undefined | null;
}

export default BdApi.Webpack.getStore('GuildStore') as GuildStore;