on:
  push:
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v18
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: npm ci
        run: npm ci
      - name: Typescript Compiler
        uses: icrawl/action-tsc@v1
      - name: Build (NCC)
        run: npx tsx ./scripts/build.ts --all
