on:
  push:
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install bun v1.1.42
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.42
      - name: bun ci
        run: bun ci
      - name: Typescript Compiler
        uses: icrawl/action-tsc@v1
      - name: Build
        run: bun ./scripts2/build.ts --all
